level-light: 7
auto-disable-time: 60
messages:
  turn-off: "&#83DE7C[✔ | AutoTorch] → You have turned off auto torch mode!"
  turn-on: "&#83DE7C[✔ | AutoTorch] → You have turned on auto torch mode! (WARNING: It will turn off automatically after a minute.)"
  auto-disable: "&#DE7C7C[✘ | AutoTorch] → Auto torch mode disabled (time expired)."
