level-light: 7
auto-disable-time: 60
messages:
  turn-off: "&a[✔ | AutoTorch] → You have turned off auto torch mode!"
  turn-on: "[✔ | AutoTorch] → You have turned on auto torch mode! (WARNING: It will turn off automatically after a minute.)"
  auto-disable: "[✘ | AutoTorch] → Auto torch mode disabled (time expired)."
